### ISSUE TITLE
Highlight multiple text lines with cursor

### ISSUE THREAD

**Issue by RoozbehFarhoodi** [KordingLab/KordingLab.github.io#10]
When you highlight more than one line somewhere in the page, it highlights the entire line (with borders), I think it should highlight the text only.

**Comment by bluenex** [comment]
If you mean the liquid tag `{% highlight %}` that is what it's supposed to do. The `{% highlight %}` tag is used for the code block as explained [here.](https://help.github.com/articles/creating-and-highlighting-code-blocks/) 

If you want to highlight some short text, try using <code>`</code> instead.

**Comment by titipata** [comment]
+1 to @bluenex that's the answer.

**Comment by RoozbehFarhoodi** [comment]
Thank you bluenex, I mean the highlight with the cursor, like the attached picture: do you know how to fix it?
<img width="1259" alt="screen shot 2016-02-10 at 11 44 07 pm" src="https://cloud.githubusercontent.com/assets/14793485/12970142/66009600-d050-11e5-8e8b-3c2fb7dbea93.png">

**Comment by titipata** [comment]
I don't have that problem in Google Chrome @RoozbehFarhoodi

**Comment by RoozbehFarhoodi** [comment]
Interesting! It is with Safar I guess..

**Comment by bluenex** [comment]
I se. Already tried on Safari and never seen this before.

**Comment by titipata** [comment]
I think this can be close
