### ISSUE TITLE
Show publishing date in blog posts and resources

### ISSUE THREAD

**Issue by daniel-acuna** [KordingLab/KordingLab.github.io#18]
Maybe?

**Comment by koerding** [comment]
sure

On Tue, Mar 15, 2016 at 5:07 PM, Daniel E. Acuna <notifications@github.com>
wrote:

> Maybe?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/KordingLab/KordingLab.github.io/issues/18>
>



-- 
I love those that desire the impossible - Goethe.

Konrad Kording @kordinglab
773 - liberat (5423728)
klab.smpp.northwestern.edu
administrative support: Mengwei Liu (mliu@ric.org)
