### ISSUE TITLE
Custom css file

### ISSUE THREAD

**Issue by titipata** [KordingLab/KordingLab.github.io#2]
- [x] adjust code section to be full width (no padding).
- [x] change display font or looking on resource page. It's now hard to watch through all the posts.

**Comment by bluenex** [comment]
For the first one, do you mean this? If yes I think this looks better than no padding.

![image](https://cloud.githubusercontent.com/assets/11027706/12841698/3e58aa9a-cc20-11e5-849b-6c44d281f6e1.png)

For the second one, it already looks good to me. We may have to discuss more on what you really need.

**Comment by titipata** [comment]
I think this can be closw
