### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by AishaWard** [KordingLab/KordingLab.github.io#34]
What is the licensing on this webpage please?

**Comment by titipata** [comment]
I believe it should be MIT license. However, if you want to get specific details of the page, feel free to discuss here :)

**Comment by AishaWard** [comment]
Is my understanding correct in that I can use a forked repository of this as long as I acknowledge the source it came from on the webpage, and that I provide the copyright notice?
Thanks

**Comment by titipata** [comment]
Yes, that should be totally fine!
