### ISSUE TITLE
Home page changes

### ISSUE THREAD

**Issue by rachit2403** [KordingLab/KordingLab.github.io#36]
Changes in homepage:

- [ ] Change group photo
- [ ] Add a news section on the home page below our address (just above the tweets). The news section will have any new accomplishments (new preprints/publications/talks/scholarships etc.) [2 month time frame]. Each member should add it themselves. This issue is just to create a section for it, and start populating it.

**Comment by aribenjamin** [comment]
I'll go ahead and change the photo

**Comment by aribenjamin** [comment]
Also I'll add the News section. I'll email around for recent things.

**Comment by aribenjamin** [comment]
Implemented in PR #45
