### ISSUE TITLE
New Blog and Resources Page

### ISSUE THREAD

**Issue by rachit2403** [KordingLab/KordingLab.github.io#41]
- [x] Merging the two pages
- [x] Emphasis on the blog, using wiseodd format
- [x] Lab teachings, below the blogs. 
- [x] Then other resources

**Comment by titipata** [comment]
Can you make a PR for this issue @rachit2403? Was it done?

**Comment by aribenjamin** [comment]
@rachit2403 yeah is it ready? I have a blog post that I want to write over break

**Comment by titipata** [comment]
I don't know what's happening here. @rachit2403 said he is going to put Ben's instructions too but if it's not happening, I can help put it on.

**Comment by titipata** [comment]
I will close this issue. Already implemented by @rachit2403, you check out the current `master` branch.
