### ISSUE TITLE
Add way to upload files and images

### ISSUE THREAD

**Issue by titipata** [KordingLab/KordingLab.github.io#5]
We will do something like this for the blog post:  https://www.maxmasnick.com/2012/01/21/jekyll_s3_cloudfront/

**Comment by daniel-acuna** [comment]
I think Konrad wants to use Github for all of this. Close?

**Comment by titipata** [comment]
This suppose to be for a bigger file. I don't think we can upload everything to the repo

**Comment by daniel-acuna** [comment]
got it. should we set up an uploader that grabs Github credentials to authenticate people from the lab? This then could produce a link ala bit.ly that people can use in Jekyll

**Comment by titipata** [comment]
@koerding will you set up cloud storage for uploading lab documents (files, pdf files and photos)? It can be on AWS S3. 

@daniel-acuna, @bluenex any suggestion?

**Comment by daniel-acuna** [comment]
I would go with S3: cheap, globally distributed, and fast. I would be happy to work on extending [prose.io](https://github.com/prose/prose) to allow uploading to S3.

**Comment by titipata** [comment]
@rachit2403 did we solve this? Why do we close this issue?
